apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-frontend
  template:
    metadata:
      labels:
        name: pod-frontend
      name: frontend
    spec:
      containers:
      - image: localhost:5000/frontend
        name: frontend
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          - name: BACKEND_URL
            value: http://localhost:8000
